name: Build
on:
  push:
    branches:
      - '**'        # matches every branch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: ./scripts/build.sh
      # - name: Test with the Go CLI
      #   run: go test